describe('fitur login', () => {
  it('Login Berhasil', () => { //Test Cases Login Berhasil
    cy.visit('https://katalon-demo-cura.herokuapp.com/')
    cy.get('#menu-toggle > .fa').click()
    cy.get('.sidebar-nav > :nth-child(4) > a').click()
    cy.get('#txt-username').type('John Doe')
    cy.get('#txt-password').type('ThisIsNotAPassword')
    cy.get('#btn-login').click()
  })
  it('Username Kosong', () => { //Test Cases Login Gagal - Username Kosong
    cy.visit('https://katalon-demo-cura.herokuapp.com/')
    cy.get('#menu-toggle > .fa').click()
    cy.get('.sidebar-nav > :nth-child(4) > a').click()
    cy.get('#txt-username')
    cy.get('#txt-password').type('ThisIsNotAPassword')
    cy.get('#btn-login').click()
  })
  it('Password Kosong', () => { //Test Cases Login Gagal - Password Kosong
    cy.visit('https://katalon-demo-cura.herokuapp.com/')
    cy.get('#menu-toggle > .fa').click()
    cy.get('.sidebar-nav > :nth-child(4) > a').click()
    cy.get('#txt-username').type('John Doe')
    cy.get('#txt-password')
    cy.get('#btn-login').click()
  })
  it('Username Salah', () => { //Test Cases Login Gagal - Username Salah
    cy.visit('https://katalon-demo-cura.herokuapp.com/')
    cy.get('#menu-toggle > .fa').click()
    cy.get('.sidebar-nav > :nth-child(4) > a').click()
    cy.get('#txt-username').type('Dawit QA')
    cy.get('#txt-password').type('ThisIsNotAPassword')
    cy.get('#btn-login').click()
  })
  it('Password Salah', () => { //Test Cases Login Gagal - Password Salah
    cy.visit('https://katalon-demo-cura.herokuapp.com/')
    cy.get('#menu-toggle > .fa').click()
    cy.get('.sidebar-nav > :nth-child(4) > a').click()
    cy.get('#txt-username').type('John Doe')
    cy.get('#txt-password').type('Password1')
    cy.get('#btn-login').click()
  })
})